import type { CatalogCategory, CatalogData, CatalogItem } from './types';

export const DEFAULT_CATEGORIES: CatalogCategory[] = [
  {
    id: 'ice-cream-sandwiches',
    name: 'Gourmet Ice Cream Sandwiches',
    description:
      'Indulge in our gourmet ice cream sandwiches, where fresh-baked cookies meet creamy ice cream for the ultimate treat.',
  },
  {
    id: 'pookies',
    name: 'Pookies',
    description:
      'A warm, half-baked cookie served with a scoop of ice cream in a bowl. These delicious treats are perfect for anyone with a sweet tooth.',
  },
  {
    id: 'ice-cream',
    name: 'Premium Ice Cream',
    description:
      'All products are made from scratch using fresh, natural ingredients. We frequently add seasonal flavors.',
  },
];

export const DEFAULT_CATALOG_ITEMS: CatalogItem[] = [
  {
    id: 'ron-burgundy',
    slug: 'ron-burgundy',
    name: 'Ron Burgundy',
    description: 'Snickerdoodle cookies with Strawberry Nutella ice cream',
    priceCents: 799,
    currency: 'USD',
    productType: 'sandwich',
    categoryId: 'ice-cream-sandwiches',
    imageUrl: null,
    isFeatured: true,
    featureRank: 1,
    isVisible: true,
    tags: ['signature'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'frequent-flyer',
    slug: 'frequent-flyer',
    name: 'Frequent Flyer',
    description: 'Snickerdoodle cookies with Biscoff ice cream',
    priceCents: 799,
    currency: 'USD',
    productType: 'sandwich',
    categoryId: 'ice-cream-sandwiches',
    imageUrl: '/assets/Product Images/FrequentFlyer.png',
    isFeatured: true,
    featureRank: 2,
    isVisible: true,
    tags: ['signature'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'luigis-mansion',
    slug: 'luigis-mansion',
    name: "Luigi's Mansion",
    description: 'Double Fudge cookies with Mint Oreo ice cream',
    priceCents: 799,
    currency: 'USD',
    productType: 'sandwich',
    categoryId: 'ice-cream-sandwiches',
    imageUrl: '/assets/Product Images/LuigisMansion.png',
    isFeatured: true,
    featureRank: 3,
    isVisible: true,
    tags: ['signature'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'golden-snitch',
    slug: 'golden-snitch',
    name: 'Golden Snitch',
    description: 'Oatmeal cookies with Honeycomb ice cream',
    priceCents: 799,
    currency: 'USD',
    productType: 'sandwich',
    categoryId: 'ice-cream-sandwiches',
    imageUrl: '/assets/Product Images/GoldenSnitch.png',
    isFeatured: false,
    featureRank: 10,
    isVisible: true,
    tags: ['signature'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'half-baked',
    slug: 'half-baked',
    name: 'Half Baked',
    description: 'Oatmeal cookies with No Bake ice cream',
    priceCents: 799,
    currency: 'USD',
    productType: 'sandwich',
    categoryId: 'ice-cream-sandwiches',
    imageUrl: '/assets/Product Images/HalfBaked.png',
    isFeatured: false,
    featureRank: 11,
    isVisible: true,
    tags: ['signature'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'inception',
    slug: 'inception',
    name: 'Inception',
    description:
      'One Chocolate Chip cookie paired with one Double Fudge cookie and Cookie Monster ice cream',
    priceCents: 849,
    currency: 'USD',
    productType: 'sandwich',
    categoryId: 'ice-cream-sandwiches',
    imageUrl: '/assets/Product Images/Inception.png',
    isFeatured: false,
    featureRank: 12,
    isVisible: true,
    tags: ['signature'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'smores-sunday',
    slug: 'smores-sunday',
    name: "S'mores Sunday",
    description:
      "Warm Chocolate Chip base topped with S'mores ice cream and caramel drizzle. Camping done right.",
    priceCents: 899,
    currency: 'USD',
    productType: 'pookie',
    categoryId: 'pookies',
    imageUrl: '/assets/Product Images/SmoreSunday.png',
    isFeatured: true,
    featureRank: 4,
    isVisible: true,
    tags: ['pookie'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'the-breakup',
    slug: 'the-breakup',
    name: 'The Breakup',
    description:
      "Warm Double Fudge base topped with Dark Chocolate Sea Salt ice cream and chocolate drizzle. He wasn't worth it. This is.",
    priceCents: 899,
    currency: 'USD',
    productType: 'pookie',
    categoryId: 'pookies',
    imageUrl: '/assets/Product Images/TheBreakup.png',
    isFeatured: false,
    featureRank: 13,
    isVisible: true,
    tags: ['pookie'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'frequent-flyer-pookie',
    slug: 'frequent-flyer-pookie',
    name: 'Frequent Flyer Pookie',
    description:
      'Warm Snickerdoodle base topped with Biscoff ice cream and caramel drizzle. See you tomorrow, and the next day.',
    priceCents: 899,
    currency: 'USD',
    productType: 'pookie',
    categoryId: 'pookies',
    imageUrl: '/assets/Product Images/FrequentFlyerPizookie.png',
    isFeatured: false,
    featureRank: 14,
    isVisible: true,
    tags: ['pookie'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'vanilla-bean',
    slug: 'vanilla-bean',
    name: 'Vanilla Bean',
    description: 'Classic vanilla bean ice cream',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 100,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'cookie-monster',
    slug: 'cookie-monster',
    name: 'Cookie Monster',
    description: 'Blue cookie-flavored ice cream with cookie pieces',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 101,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'dark-chocolate-sea-salt',
    slug: 'dark-chocolate-sea-salt',
    name: 'Dark Chocolate Sea Salt',
    description: 'Rich dark chocolate with a hint of sea salt',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 102,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'birthday-cake',
    slug: 'birthday-cake',
    name: 'Birthday Cake',
    description: 'Vanilla cake batter ice cream with sprinkles',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 103,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'strawberry-nutella',
    slug: 'strawberry-nutella',
    name: 'Strawberry Nutella',
    description: 'Strawberry ice cream swirled with Nutella',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 104,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'mint-oreo',
    slug: 'mint-oreo',
    name: 'Mint Oreo',
    description: 'Mint ice cream with Oreo cookie pieces',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 105,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'biscoff',
    slug: 'biscoff',
    name: 'Biscoff',
    description: 'Creamy Biscoff cookie butter ice cream',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 106,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
  {
    id: 'honeycomb',
    slug: 'honeycomb',
    name: 'Honeycomb',
    description: 'Sweet honey ice cream with honeycomb candy',
    priceCents: 499,
    currency: 'USD',
    productType: 'ice-cream',
    categoryId: 'ice-cream',
    imageUrl: null,
    isFeatured: false,
    featureRank: 107,
    isVisible: true,
    tags: ['ice-cream'],
    squareItemId: null,
    squareVariationId: null,
  },
];

export function getDefaultCatalogData(): CatalogData {
  return {
    source: 'fallback',
    syncedAt: null,
    categories: DEFAULT_CATEGORIES,
    items: DEFAULT_CATALOG_ITEMS,
  };
}
